services:
#    ben_doctors.example:
#        class: Ben\DoctorsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ben.twig.extension.config:
        class: Ben\DoctorsBundle\Twig\ConfigExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }