antecedent:
    path:     /
    defaults: { _controller: "BenDoctorsBundle:Antecedent:index" }

antecedent_show:
    path:     /{id}/show
    defaults: { _controller: "BenDoctorsBundle:Antecedent:show" }

antecedent_new:
    path:     /{id}/new
    defaults: { _controller: "BenDoctorsBundle:Antecedent:new" }

antecedent_create:
    path:     /create
    defaults: { _controller: "BenDoctorsBundle:Antecedent:create" }
    requirements: { _method: post }

antecedent_edit:
    path:     /{id}/edit
    defaults: { _controller: "BenDoctorsBundle:Antecedent:edit" }

antecedent_update:
    path:     /{id}/update
    defaults: { _controller: "BenDoctorsBundle:Antecedent:update" }
    requirements: { _method: post|put }

antecedent_delete:
    path:     /{id}/delete
    defaults: { _controller: "BenDoctorsBundle:Antecedent:delete" }
    requirements: { _method: post|delete }
